version: '3'

services:
  web-api:
    image: davidkroell/keylog.rest
    container_name: keylog.rest-api
    restart: always
    environment:
      NODE_ENV: production
      # use this if you are behind a proxy, this is the header, which the proxy sets
      PROXY_HEADER_REAL_IP_KEY: x-real-ip # for jwilder/nginx-proxy
    ports:
      - 3000:3000
    networks:
      - mysql
    volumes:
      - "./config.example.docker.js:/usr/src/app/config.js:ro" # customize
      # - "/path/to/payloads:/usr/src/app:ro"
    depends_on:
      - "mysql"
  mysql:
    image: mysql
    container_name: keylog.rest-db
    restart: always
    environment: ### customize
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "keylogger"
      MYSQL_USER: "keylog_user"
      MYSQL_PASSWORD: "secret"

networks:
  mysql:
  