version: '2.1'

services:
  keylog.rest:
    image: keylog.rest
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect ./bin/www